#!/usr/bin/env python3
"""Prepare transparent provenance for room requests; does not call an API."""
import json
from pathlib import Path

PACK=Path(__file__).resolve().parents[1]/'public/mods/gpt-image-2-pack'
SCENES={
 'antimeme-division':('逆模因部','Sunlit secure memory archive room, ivory record cabinets and shelves of sealed memory medicine vials at the sides, pale cyan mechanical memory apparatus, translucent blank panels fading subtly at the far edge; welcoming scientific institution, clear wall center.'),
 'chen-sheng-uprising':('等死死国可乎','Qin dynasty roadside military waystation during rain, front-elevation timber awning, bamboo bundles and rain cloaks at the sides, weathered clay wall, spear rack and rolled woven mats, empty center; misty daylight and golden lanterns, historically Chinese setting, no European castles.'),
 'collapse':('崩溃','A university student study-and-work room, small cluttered desk with stacked textbooks at one side, packed lunch and work apron on pegs at the other, blank calendar sheets, large warm daylight window, mismatched shelf, clear central walking area; visual strain through many objects not darkness.'),
 'consumerism-magic':('消费主义魔法','Fantasy magic merchant shop frontage, shelves of colorful potion bottles and magical consumer goods at both sides, ornate blank hanging ad boards, glowing crystal display and gift boxes, pastel guild architecture, broad empty sidewalk center, sunny honey and lavender palette.'),
 'crowd':('人从众','Sunny modern pedestrian shopping street viewed perpendicular to the storefronts, cream shop facades with large blank ad panels, colorful goods display at one side, vending machines and distant factory smokestack shapes behind skyline, broad uncluttered central sidewalk, no crowd painted in.'),
 'cthulhu':('克苏鲁神话','A forbidden-knowledge seaside mansion library, deep teal bookcases and warm ochre carved wood, one strange CLOSED ancient dark book on a pedestal near the side, seashell and star-map ornaments without readable symbols, daylight windows facing calm sea; uncanny but bright readable not horror-dark.'),
 'cyber-dream':('赛博梦中梦','Layered virtual reality chamber: pale violet futuristic wall with nested rounded portal frames seen straight-on, soft mint translucent mechanical partitions, blue-sky digital gardens visible in windows, one empty VR pod at the side, playful dreamlike reflections, no perspective tunnel, broad clear central walking platform.'),
 'destroy-hive-mind':('毁灭虫族主脑','Liangzhu energy company command atrium 4C in an East Asian ancient-style sci-fi fusion power station, jade columns with futuristic amber reactor conduits and mint control cabinets at the sides, decorative curved eaves, circular sealed biological-network interface visible on back wall, no living creatures; daylight industrial ancient-future mix, not a generic bug cave.'),
 'face-saving':('死要面子活受罪','Spring-and-Autumn era Chinese royal audience hall, symmetrical vermilion wooden columns, gilded traditional bracket detail, jade ritual vessels and one empty royal seat toward side, woven screens, broad clear audience platform, warm daylight; Chinese court identity, no European throne or random classroom.'),
 'hive-self':('集群意识','Small shared habitat for three identical clones, exactly three compact storage lockers and three folded sleeping alcoves against back wall, visibly scarce shared supply shelf with a few food tins at one side, communal table at other side, clean pale mint science-fiction architecture, bright but modest, center unobstructed.'),
 'ideology':('信仰与意识形态','Community assembly hall for belief discussion, warm timber wall, colorful plain fabric banners without symbols, noticeboard with blank pinned sheets, bookcase and small debate lectern at the far edges, sunlight through tall windows, open gathering platform in center, inclusive architecture no specific religious emblem.'),
 'illusion-trap':('幻境挣扎','Beautiful misleading enchanted garden stage with pale peach flowering trees, ornate ivory garden wall, dreamlike pastel cloud window openings, gentle crystal fragments and faint fractured-reflection accents at far sides indicating hidden reality, clear grass-topped platform, magical daylight no characters.'),
 'internet-addict':('网瘾少年','A teenage gamers sunny bedroom: mint-glowing computer monitor with no UI at side desk, game controller and headset on shelf, unattended schoolbooks and sports ball near other side, cozy bed edge and warm blue-sky window, broad clear middle wall and walkable wood strip, virtual green accents balanced with real warm daylight.'),
 'meme-magic':('模因和魔法','Fantasy cognitive meme engineering laboratory, brass and mint apparatus behind glass at side, glowing crystals linked by decorative filaments on back wall, sealed specimen cabinets, blank cards and covered visual-trigger display panels, sunlight through high windows, clearly different from ordinary chemistry room, open central floor.'),
 'postmodern-vagrant':('后现代解构流浪','Bright outdoor mutual-aid vagabond settlement near an automated future city, handmade timber shelters at the sides, cooking pot on communal stove and shared tool rack, patchwork fabric awning, vegetable crates, small garden glimpses behind back fence; dignity cooperation and participation, no people, open horizontal path.'),
 'trigger-addiction':('触发网瘾','Futuristic brain-interface induction room: empty reclining neural interface chair at far side, pale teal server cabinets and reward-light crystals on wall, framed blank virtual-world window, restrained glowing green and peach circuits, broad clear center; inviting yet subtly artificial, no screen UI.'),
 'water-is-poison':('水是有毒的','Bright cognitive belief-imprinting experiment laboratory: empty thought-imprint helmet machine on side stand, transparent water carafe and glass on narrow side table, dry bread and small oven on other side, pale blue clean wall and sunny windows, broad central space, water visibly ordinary not poison sludge.'),
}
COMMON='Use case: stylized-concept. Asset type: production background for a 2D horizontal side-scrolling game, landscape 3:2. Bright exquisite hand-painted anime RPG illustration, cheerful polished LaTale and MapleStory visual language, warm crisp outlines, beautiful detailed but readable props. STRICT ORTHOGRAPHIC SIDE ELEVATION like a theatre stage viewed directly perpendicular to the back wall: all furniture and architecture fronts parallel to canvas. NO receding floor plane, perspective vanishing points, isometric/top-down camera, diagonal floor, side walls or tunnel. A single perfectly horizontal ground baseline exactly 85 percent of canvas height, thin walkable platform top and flat vertical platform front below. Leave middle 60 percent clear for movable four-head-tall actors. No characters, people, animals, humanoid silhouettes, words, text, letters, numbers, logos, watermark, UI or diagram overlays. Scene must be this particular narrative setting, not a reused classroom. '
def main():
    old=json.loads((PACK/'manifest.json').read_text())
    sources={i['levelId']:i for i in old['items'] if i['type']=='background'}
    jobs=[]
    for level,(title,scene) in SCENES.items():
        jobs.append({'levelId':level,'title':title,'output':f'rooms/{level}.png','prompt':COMMON+'Scene/backdrop: '+scene+' Narrative context for location only: '+sources[level]['sourcePrompt']+' Final constraints: environment only; strictly horizontal single platform; no drawn actors or readable text.','sourcePrompt':sources[level]['sourcePrompt'],'wiki':f'wiki/tiddlers/{title}.tid','generator':'proxy-imagegen','model':'gpt-image-2','outerModel':'gpt-6.1-sol','provider':'https://token.k3s.onetwo.website/v1','attemptLimit':3})
    (PACK/'sideview/room-jobs.json').write_text(json.dumps(jobs,ensure_ascii=False,indent=2)+'\n')
    print(f'{len(jobs)} scene-specific prompts prepared, no API called')
if __name__=='__main__':main()
